pipeline:

  create-docker-image:
    image: docker:17.09.0-ce
    environment:
      - DOCKER_HOST=tcp://127.17.0.1:2375
    commands:
      - docker build -t pttg-vault-sidekick .
    when:
      event: [push, pull_request]

  push-image-to-quay:
    image: docker:17.09.0-ce
    environment:
      - DOCKER_HOST=tcp://127.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=${DOCKER_PASSWORD} quay.io
      - docker tag pttg-vault-sidekick quay.io/ukhomeofficedigital/pttg-vault-sidekick:build-${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/pttg-vault-sidekick:build-${DRONE_BUILD_NUMBER}
    when:
      branch: [master]
      event: [push]